### ISSUE TITLE
use existing iainkirkpatrick/dogstack repo?

### ISSUE THREAD

**Issue by ahdinosaur** [enspiral-root-systems/dogstack#1]
@iainkirkpatrick hey, do you think we move your original https://github.com/iainkirkpatrick/dogstack as the starting point here?

would mean we delete this repo and you transfer yours to the Root Systems org.

**Comment by iainkirkpatrick** [comment]
Agree - not sure there is a lot we'll end up keeping but the README is even just a nice kicking-off point.
Will move.
