### ISSUE TITLE
Cannot find module 'dogstack/createStyleRenderer'

### ISSUE THREAD

**Issue by agentlewis** [enspiral-root-systems/dogstack#64]
I pulled the example app and got this error on yarn dev.

I looked into the code and can see that the createStyle is not included in the module export in the index.js file of dogstack. Thought this might be the problem, but still didn't get it working when i changed this.

So Ill just put it here as its probably an easy fix for you @ahdinosaur

**Comment by ahdinosaur** [comment]
hey @agentlewis, thanks for the bug report. i know _how_ this could happen on my work in progress releases, but not sure how this would happen now that i've published `0.2.0`. do you have a stack trace for this error?

**Comment by ahdinosaur** [comment]
oh wait oops, duh: https://github.com/enspiral-root-systems/dogstack/blob/master/entry.js#L12

one moment please. :smile_cat:

**Comment by ahdinosaur** [comment]
@agentlewis see if this is fixed meow, works for me on a fresh install at https://github.com/dogstack/dogstack-example/commit/7d5618695b3de552d07cc4472a33b9e438303b07.
